services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rtech_bms_server
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_PORT: ${MYSQL_TCP_PORT}
      DB_USER: ${MYSQL_ROOT_USER}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      DB_HOST: ${DB_DOCKER_HOST}
      BASE_API: ${BASE_API}
      REDIS_HOST: ${DOCKER_REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      COMPANY_NAME: ${COMPANY_NAME}
      BASE_FRONT_URL: ${BASE_FRONT_URL}
      EN_SECRET_KEY: ${EN_SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH: ${JWT_REFRESH}
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUD_API_KEY: ${CLOUD_API_KEY}
      CLOUD_API_SECRET: ${CLOUD_API_SECRET}
      CLOUD_MAIN_FOLDER: ${CLOUD_MAIN_FOLDER}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${FIREBASE_APP_ID}
      FIREBASE_MEASUREMENT_ID: ${FIREBASE_MEASUREMENT_ID}
      FIREBASE_SERVICE_TYPE: ${FIREBASE_SERVICE_TYPE}
      FIREBASE_SERVICE_PROJECT_ID: ${FIREBASE_SERVICE_PROJECT_ID}
      FIREBASE_SERVICE_PRIVATE_KEY_ID: ${FIREBASE_SERVICE_PRIVATE_KEY_ID}
      FIREBASE_SERVICE_PRIVATE_KEY: ${FIREBASE_SERVICE_PRIVATE_KEY}
      FIREBASE_SERVICE_CLIENT_EMAIL: ${FIREBASE_SERVICE_CLIENT_EMAIL}
      FIREBASE_SERVICE_CLIENT_ID: ${FIREBASE_SERVICE_CLIENT_ID}
      FIREBASE_SERVICE_AUTH_URI: ${FIREBASE_SERVICE_AUTH_URI}
      FIREBASE_SERVICE_TOKEN_URI: ${FIREBASE_SERVICE_TOKEN_URI}
      FIREBASE_SERVICE_AUTH_PROVIDER_X509_CERT_URL: ${FIREBASE_SERVICE_AUTH_PROVIDER_X509_CERT_URL}
      FIREBASE_SERVICE_CLIENT_X509_CERT_URL: ${FIREBASE_SERVICE_CLIENT_X509_CERT_URL}
      FIREBASE_SERVICE_UNIVERSE_DOMAIN: ${FIREBASE_SERVICE_UNIVERSE_DOMAIN}
      FIREBASE_VAPID: ${FIREBASE_VAPID}
      RMQ_URL: ${DOCKER_RMQ_URL}
      RMQ_USER_NAME: ${RMQ_USER_NAME}
      RMQ_USER_PASSWORD: ${RMQ_USER_PASSWORD}
      RMQ_NOT_USER: ${RMQ_NOT_USER}
      RMQ_NOT_PASS: ${RMQ_NOT_PASS}
      RMQ_PORT: ${RMQ_PORT}
      RMQ_HOST: ${RMQ_HOST}
      SOCKET_TOKEN: ${SOCKET_TOKEN}
    ports:
      - 3600:3600
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - rtech_bms_network
