export enum NOTIFICATION_PATTERN {
  NOTIFY = 'notify',
  SYSTEM_NOTIFICATION = 'SYSTEM_NOTIFICATION',
  ANNOUNCEMENTS = 'announcements',
  LOGIN = 'login',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  RESEND = 'RESEND',
}
